"
" dotphiles : https://github.com/dotphiles/dotphiles
"
" Setup vim and load required plugins before dotvim
"
" Authors:
"   Ben O'Hara <bohara@gmail.com>
"

" Customize to your needs...
set nocompatible
set mouse=
syntax on

set background=dark
colorscheme sunburst
filetype plugin indent on
